# Numpy

In [1]:
import numpy as np

# Creating Arrays

In [17]:
mylist = [1,2,3,4,5,6,7,8,9,10]
x = np.array(mylist)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
mylisT = [11,12,13,14,15,16,17,18,19,20]
y =np.array(mylisT)
y


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
m = np.array([mylist,mylisT])
m

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [21]:
m.shape
#This gives the dimention of array

(2, 10)

In [32]:
n = np.arange(0,32,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [36]:
n = n.reshape(4,4)
n[-1][-1]

30

In [43]:
o = np.linspace(1,10,10)
o

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [46]:
o.reshape(5,2)

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [50]:
o.resize(5,2)
o

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [58]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
np.diag(x)

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10]])

In [4]:
np.array([1,2,3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [6]:
np.repeat([1,2,3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [14]:
p = np.ones([3,3],int)
p

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [16]:
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [21]:
np.vstack([mylist,mylisT])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [23]:
np.hstack([mylist,mylisT])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# OPERATIONS

In [28]:
mylist+mylisT

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [31]:
x + y

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [33]:
x * y

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [34]:
x ** y

array([                  1,                4096,             1594323,
                 268435456,         30517578125,       2821109907456,
           232630513987207,   18014398509481984, 1350851717672992089,
       7766279631452241920])

In [36]:
x.dot(y)

935

In [39]:
z = np.array([y,y**2])
z

array([[ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [121, 144, 169, 196, 225, 256, 289, 324, 361, 400]])

In [40]:
z.shape


(2, 10)

In [43]:
z.T

array([[ 11, 121],
       [ 12, 144],
       [ 13, 169],
       [ 14, 196],
       [ 15, 225],
       [ 16, 256],
       [ 17, 289],
       [ 18, 324],
       [ 19, 361],
       [ 20, 400]])

In [45]:
z.dtype

dtype('int64')

In [46]:
z = z.astype('f')

In [47]:
z.dtype

dtype('float32')

In [48]:
z

array([[ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [121., 144., 169., 196., 225., 256., 289., 324., 361., 400.]],
      dtype=float32)

In [49]:
z = z.astype('i')

In [50]:
z

array([[ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [121, 144, 169, 196, 225, 256, 289, 324, 361, 400]], dtype=int32)

In [7]:
a = [1,2,3,4]
a = np.array([a])
a

array([[1, 2, 3, 4]])

In [10]:
a.min()

1

In [11]:
a.max()

4

In [12]:
a.sum()

10

In [13]:
a.mean()

2.5

In [14]:
a.std()

1.118033988749895

In [16]:
a.argmax() 
#to find maximum values index position

3

In [18]:
a.argmin()
#to find min values index position

0

# Indexing/Slicing

In [20]:
t = np.arange(13)**2
t

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [28]:
t[0], t[4], t[1:6]

(0, 16, array([ 1,  4,  9, 16, 25]))

In [30]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [32]:
r[2,2]

14

In [34]:
r[3,3:6]

array([21, 22, 23])

In [36]:
r[-1]

array([30, 31, 32, 33, 34, 35])

In [38]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [40]:
r[-1,::2]

array([30, 32, 34])

In [41]:
r[r>30]

array([31, 32, 33, 34, 35])

In [55]:
r[r>30] = 30

r

array([[ 1,  1,  1,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [54]:
r[r==30] = [30,31,32,33,34,35]
r

ValueError: NumPy boolean array indexing assignment cannot assign 6 input values to the 1 output values where the mask is true

In [46]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [48]:
r2[:]=0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [49]:
r2 = r[:3,:3]
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [53]:
r2[0] = 1
r2

array([[1, 1, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [60]:
old = np.array([[1,1,1],[1,1,1]])
new = old.copy()
new[1:,0] = 0
print(old)

[[1 1 1]
 [1 1 1]]


# Iterating Over Arrays

In [62]:
test = np.random.randint(0,10,(4,3))
test

array([[4, 4, 4],
       [0, 3, 6],
       [1, 9, 0],
       [5, 1, 1]])

In [64]:
for row in test:
    print(row)

[4 4 4]
[0 3 6]
[1 9 0]
[5 1 1]


In [68]:
for i in range(len(test)):
    print(i)

0
1
2
3


In [71]:
for i,row in enumerate(test):
    print('row',i , 'is', row)
    #enumerate is the combination of both 

row 0 is [4 4 4]
row 1 is [0 3 6]
row 2 is [1 9 0]
row 3 is [5 1 1]


In [70]:
len(test)

4

In [73]:
test2 = test**2
test2

array([[16, 16, 16],
       [ 0,  9, 36],
       [ 1, 81,  0],
       [25,  1,  1]])

In [75]:
for i,j in zip(test,test2):
    print(i,'+', j, '=',i+j)
    #zip allows to iterate in both the arrays

[4 4 4] + [16 16 16] = [20 20 20]
[0 3 6] + [ 0  9 36] = [ 0 12 42]
[1 9 0] + [ 1 81  0] = [ 2 90  0]
[5 1 1] + [25  1  1] = [30  2  2]


In [78]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [85]:
r[2:4,2:4]

array([[14, 15],
       [20, 21]])